<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>VpnUs.Service</RootNamespace>
    <AssemblyName>VpnUs.Service</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VpnUs.Core\VpnUs.Core.csproj" />
  </ItemGroup>

</Project>
